### ISSUE TITLE
e.getPlayer() is always null when using the ChestSortEvent (in a chest)

### ISSUE THREAD

**Issue by rockyhawk64** [JEFF-Media-GbR/ChestSort#125]
**Used ChestSort version**
Tell us your ChestSort version
11.0.3

**Used Spigot version**
Tell us your Spigot version (output of /version). Please also tell us if you use another fork like Paper, etc.
Paper-49

**Describe the bug**
This is the developer of CommandPanels. I have updated the plugin to support the new API class location, however I have users who are reporting this error: https://pastebin.com/raw/nKTe9Pqd
When sorting a chest e.getPlayer() is always null for the ChestSortEvent.

**To Reproduce**
How can the behaviour be reproduced?
By sorting a chest and having a plugin using e.getPlayer()

**Expected behavior**
NullPointerException

**Additional context**

**Comment by mfnalex** [comment]
Hi, it's not a bug, although I admit it's confusing.

ChestSortEvent#getPlayer is @Nullable:
https://repo.jeff-media.com/javadocs/ChestSortAPI/de/jeff_media/chestsort/api/ChestSortEvent.html#getPlayer()

The player is only set by ChestSort when a player sorts their own inventory. Is there any need why you need to get the player that triggered sorting? If so I can just add that.
