### ISSUE TITLE
A simple little question

### ISSUE THREAD

**Issue by Zz-886** [JEFF-Media-GbR/ChestSort#126]
Hello, I want players to use hotkey, VIP use automatic, I don’t know how to set it up.
For translation reasons, I have tried several feasible solutions, but none of them work

**Comment by Zz-886** [comment]
And I found that the damaged box cannot be restored immediately

**Comment by mfnalex** [comment]
hi, there currently is no permission for automatic sorting, but I could add it.

What exactly are you meaning with "none of them work" regarding translations?

Feel free to join my discord and open a ticket: https://discord.jeff-media.com

**Comment by Zz-886** [comment]
I am looking for a way to make VIP use automatic sorting
Sorry, I tried several solutions and don’t know how to set it up

**Comment by mfnalex** [comment]
You can use version 11.2.0. There's a new permission "chestsort.automatic" that's true by default. Just deny that permission for your non-VIP players.
