### ISSUE TITLE
Unresolved needs

### ISSUE THREAD

**Issue by Zz-886** [JEFF-Media-GbR/ChestSort#128]
Give the default group chestsort.use and chestsort.use.inventory
They can use /isort on and /sort on which is not what I want.
I think it can be simpler. By default, all players can use the buttons without setting any permissions.
For groups or players with chestsort.use and chestsort.use.inventory, automatic sorting is allowed

**Comment by Cazcez** [comment]
Can you please send output of "/ver" and /ver chestsort" commands?

**Comment by Zz-886** [comment]
![image](https://user-images.githubusercontent.com/55978588/126240081-13bf4945-626e-418e-a5f8-9d2c13efdb72.png)

**Comment by mfnalex** [comment]
> Give the default group chestsort.use and chestsort.use.inventory
> They can use /isort on and /sort on which is not what I want.
> I think it can be simpler. By default, all players can use the buttons without setting any permissions.
> For groups or players with chestsort.use and chestsort.use.inventory, automatic sorting is allowed

What is it what you want instead? I don't really understand the behaviour you're expecting.

**Comment by mfnalex** [comment]
Many people need the permissions feature because they only allow sorting for VIPs etc. You can use the chestsort.automatic permission to allow/disallow automatic sorting while still allowing hotkeys

**Comment by Zz-886** [comment]
I give players chestsort.use and chestsort.use.inventory they can use /isort on and /sort on to turn on automatic sorting

**Comment by Zz-886** [comment]
![image](https://user-images.githubusercontent.com/55978588/126326504-701d77f8-a20f-4738-a841-50583072967e.png)

**Comment by mfnalex** [comment]
> I give players chestsort.use and chestsort.use.inventory they can use the /isort on and /sort on commands to turn on automatic sorting

You have to deny the angelchest.automatic permission for those players

**Comment by mfnalex** [comment]
E.g. /luckperms group default permission set angelchest.automatic false

**Comment by Zz-886** [comment]
Solved, I still want to say that the button should be owned by the player by default. If the player is not allowed to use the button, they will also download the mods for use.
So chestsort.use and chestsort.use.inventory should not contain /isort on and /sort on.
We should set the two commands /isort auto and /sort auto to control the switch of automatic sorting and set permissions for them.

**Comment by mfnalex** [comment]
I don't think so, in my opinion admins should have 100% control over the features a player has access to. Giving permissions by default can result in angry admins that want to allow features only for VIPs. The behaviour you wanted to have can be achieved by using exactly three permissions: chestsort.use (allow), chestsort.use.inventory (allow) and chestsort.automatic (deny).

Also I don't see any reason to change the current commands. /sort (and /isort on|off) toggles automatic sorting, hotkeys can be used to sort manually.
