### ISSUE TITLE
Warning while loading class from placeholderAPI

### ISSUE THREAD

**Issue by DeathDragonAW** [JEFF-Media-GbR/ChestSort#129]
**Used ChestSort version**
v11.2.1

**Used Spigot version**
Paper version git-Paper-112 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: bc127ea)

**Other plugin used**
https://github.com/PlaceholderAPI/PlaceholderAPI

**Describe the bug**
[Server thread/WARN]: [ChestSort] Loaded class me.clip.placeholderapi.expansion.PlaceholderExpansion from PlaceholderAPI v2.10.9 which is not a depend, softdepend or loadbefore of this plugin.

**To Reproduce**
Every server startup

**Expected behavior**
No warning

**Additional context**
-

**Comment by mfnalex** [comment]
Thanks, will be fixed! It's not a problem though, just a "cosmetic" warning.

**Comment by mfnalex** [comment]
@Cazcez Why do you add todo and assign me after I already closed it lol
