### ISSUE TITLE
Could not pass event InventoryCloseEvent

### ISSUE THREAD

**Issue by Bloodlex** [JEFF-Media-GbR/ChestSort#132]
**Used ChestSort version**
11.4.0

**Used Spigot version**
git-Purpur-1060 (MC: 1.16.5)

**Describe the bug**
Chest/Inventory is not sorted and an exception is thrown.
[https://pastebin.com/qDQVe14Z](https://pastebin.com/qDQVe14Z)

**To Reproduce**
1. Install the newest version
2. Try to sort something

**Expected behavior**
It should be sorted.

**Comment by Bloodlex** [comment]
Sorry, my mistake

**Comment by mfnalex** [comment]
What was the problem? ^^
