### ISSUE TITLE
ChestSort broken with SlimeFun due to update

### ISSUE THREAD

**Issue by bunnkywhat** [JEFF-Media-GbR/ChestSort#135]
**Used ChestSort version**
11.4.0

**Used Spigot version**
Paper version git-Paper-788

**Other plugin used**
Slimefun - https://github.com/Slimefun/Slimefun4

**Describe the bug**
Slimefun just updated and changed a lot of important code. ChestSort throws errors anytime it tries to sort a Slimefun Item. It also has a problem with Slimefun backpacks.

**To Reproduce**
Sort your inventory/chest with Slimefun items in it

**Expected behavior**
Normal sorting

**Additional context**
Errors:
https://paste.ofcode.org/RycAKmHwCAzfQeAAfZKiHB
https://paste.ofcode.org/B2CNqmd6r5jxpHFPLgiPNE
https://paste.ofcode.org/jtDKAhC9sntwezksNU2yCY

**Comment by mfnalex** [comment]
Update was released yesterday :)
