### ISSUE TITLE
Error ShadowPlayer@5720cc1d

### ISSUE THREAD

**Issue by broken1arrow** [JEFF-Media-GbR/ChestSort#137]
**Used ChestSort version**
 is 11.5.4 or 11.5.3

**Used Spigot version**
1.16.5 paper 718

**Describe the bug**
https://pastebin.com/jcT8mfYK

**To Reproduce**
has own method to update inventory

**Expected behavior**
no error

**Additional context**
Some way to detect this fake player, so I not get thew error.

**Comment by mfnalex** [comment]
> > Hi, update to the latest version
> 
> New bug. open inventory when break chest, on your newest version.

Can't reproduce. Can you please join my discord? I need a bit more information. Do you by any case have a plugin installed that lets you "silently" open chests or something? https://discord.jeff-media.com

**Comment by mfnalex** [comment]
no reply within 365 days

**Comment by broken1arrow** [comment]
Yeah I even forget this thread. I think we solved this on discord.
