### ISSUE TITLE
ChestSort not working (with ShulkerPacks)

### ISSUE THREAD

**Issue by Bloodlex** [JEFF-Media-GbR/ChestSort#140]
**Used ChestSort version**
12.1.1-12.1.3

**Used Spigot version**
git-Purpur-"4ff0630" (MC: 1.17.1) (last after log4j hotfix from December 10.

**Describe the bug**
No sorting works. It may be a new integration with Shulker Backpacks from version 12.1.1 onwards.

**To Reproduce**
1. Install Shulker Backpacks 1.6.1 (I suspect this may be a reason) and ChestSort 12.1.1/12.1.2/12.1.3
2. Try to sort.
3. Nothing happens, exception is thrown.

**Expected behavior**
Sorting should work like in previous version (12.1.0 was the last working version)

**Additional context**
Exception log: [https://pastebin.com/HJ9pxrS8](https://pastebin.com/HJ9pxrS8)

Other plugins:
Plugins (72): ActionHealth, AdvancedChests, AdvancedLogger*, AdvancedRegionMarket, ajParkour, AntiWorldFly, ArmShopBridge, AureliumSkills, AuthMe, BetterHeads, ChatEmojis, ChestSort, Cigarette, ClearLag, CMI, CMILib, CommandNotifier, CommandPanels, CoordsManager, CraftBook, DeathPenalties, DiscordSRV, dynmap, Dynmap-WorldGuard*, EasyCarts, Epidemic, EvenMoreFish, ExcellentEnchants, GSit, Harbor, HolographicDisplays, Images, InteractionVisualizer, ItemFrameToggle, Jobs, KauriVPN, KelpEffect, LangUtils, LogBlock, LuckPerms, LWC, LWCTrust, MobArena, MyCommand, NBTAPI, NexEngine, NoElytra*, PL-Hide-Pro, PlaceholderAPI, Plan, PortalFix*, ProtocolLib, PvPManager, QuickShop, RegionRaid, SelectionVisualizer, ShulkerPacks, SkinsRestorer, Spartan, StarMail, SuperVanish, TAB, TitleManager, TradingCards, Unstripper, Vault, Vegas, Vehicles, VehiclesFlags, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Comment by mfnalex** [comment]
Update to latest ShulkerPacks and latest ChestSort and it'll work fine. ShulkerPacks just got a new update and it will work fine.
