### ISSUE TITLE
1.18 Update broke middle click sorting

### ISSUE THREAD

**Issue by dfeneck** [JEFF-Media-GbR/ChestSort#142]
**Used ChestSort version**
1.18

**Used Spigot version**
Latest 1.18

**Describe the bug**
I use the "middle click on any slot" feature to sort my items, however after the update this feature stopped working. Interestingly though, if you grab an item, then middle click on a container, it will sort, just without the item you had picked up!

**To Reproduce**
Attempt to sort a chest with middle click.

**Expected behavior**
It won't sort.

**Additional context**
I am running a bunch of other mods, but it was never an issue before the latest updates to 1.18.

**Comment by mfnalex** [comment]
Middle Click on empty slots was removed from Vanilla MC and will be replaced with another hotkey in future CHestSort versions: https://www.spigotmc.org/threads/chestsort-api.334121/page-33#post-4315197
