### ISSUE TITLE
Not  currently working with CosmicVaults 3.3.0

### ISSUE THREAD

**Issue by MTDeath** [JEFF-Media-GbR/ChestSort#144]
Awesome plugin, wish it would work for CosmicVaults, another good plugin for small servers.

The /pv (Player vaults) are not able to be sorted / filled.

Plugin: https://www.spigotmc.org/resources/cosmic-vaults.45463/

**Comment by mfnalex** [comment]
Hi, can you please enable debug mode (`/sort debug`), then try to use a hotkey inside a player vault, and then send the console output?

**Comment by mfnalex** [comment]
Thanks. Unfortunately, the plugin you mentioned uses the player as InventoryHolder, so ChestSort cannot detect that it's a custom plugin's GUI. You can ask the author of that plugin to make the inventory sortable using ChestSort's API: https://github.com/JEFF-Media-GbR/ChestSort/blob/33283a3360e6cdbb1c266b4f973a7d4cadf1a7df/src/main/java/de/jeff_media/chestsort/api/ChestSortAPI.java#L21

**Comment by mfnalex** [comment]
Information about the API can be found here: https://github.com/JEFF-Media-GbR/ChestSort/blob/master/HOW_TO_USE_API.md

**Comment by MTDeath** [comment]
CosmicVault changed their plugin and it allows the sorting now (dblclicking while in the PlayerVault gui sorts the PlayerVault) but the HotKeys outside the GUI are not processed to move the items:

[22:44:53 WARN]: [ChestSort] [DEBUG] InventoryClickEvent:
[22:44:53 WARN]: [ChestSort] [DEBUG] - Holder: CraftPlayer{name=MTDeath}
[22:44:53 WARN]: [ChestSort] [DEBUG] - Holder class: class org.bukkit.craftbukkit.v1_18_R1.entity.CraftPlayer
[22:44:53 WARN]: [ChestSort] [DEBUG] - Slot: -999
[22:44:53 WARN]: [ChestSort] [DEBUG] - Left-Click: true
[22:44:53 WARN]: [ChestSort] [DEBUG] - Right-Click: false
[22:44:53 WARN]: [ChestSort] [DEBUG] - Shift-Click: false

What else needs to be done to allow the Hotkeys outside the Gui?
