### ISSUE TITLE
Hoppers are not sorted / filled 

### ISSUE THREAD

**Issue by MTDeath** [JEFF-Media-GbR/ChestSort#145]
ChestSort-12.1.4

Paper version git-Paper-169 (MC: 1.18.1) 
(Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 60e46ab)

Vanilla hoppers are not sorted / filled

Try it :)

Fill matching items on click outside gui

Maybe make it option in the config?

**Comment by mfnalex** [comment]
Hi, this is on purpose because it would destroy vanilla "hopper sorting machines". Stuff like this -> https://www.youtube.com/watch?v=AHRax2YEkdo

**Comment by MTDeath** [comment]
Thank you for replying and explaining your close.

**Comment by mfnalex** [comment]
I could add a config option to allow sorting hoppers if you like, but as I said - keep in mind that many players do not want hoppers being sorted in the first place :) Let me know if you still like me to add it :)

**Comment by mfnalex** [comment]
Information about the API can be found here: https://github.com/JEFF-Media-GbR/ChestSort/blob/master/HOW_TO_USE_API.md

**Comment by MTDeath** [comment]
If you could add this it would be great, with default "Off" it should only affect those that want to use it.
