### ISSUE TITLE
LWC Compatibility.

### ISSUE THREAD

**Issue by andrewkm** [JEFF-Media-GbR/ChestSort#151]
Can we perhaps get some compatibility with LWCX (https://github.com/pop4959/LWCX)
This is in regards to LWC's "display" and "donation" chests.
Users have access to those chests to view but not move/take (display chests) as well as place items in but not take out (donation chests).
Would be nice if ChestSort did not auto sort those chests, as they technically (according to LWC of course) do not belong to that user.

CC: @pop4959 (tagging in-case perhaps this is something LWCX can do on it's end)?

**Comment by mfnalex** [comment]
Hi, I cannot possibly add support for all 3rd party plugins. There's the ChestSort that can be used make custom inventories, sortable, or prevent them from being sorted, and also to prevent certain items from being moved at all, etc: https://github.com/JEFF-Media-GbR/ChestSort/blob/master/HOW_TO_USE_API.md

If you need other plugins to get ChestSort integration, send them this link :) Feel free to reopen this issue if there's any further questions, but as said - I cannot look into all 3rd party plugins, they are advised to use the ChestSort API instead :)
