### ISSUE TITLE
Does not seem to work with Sack

### ISSUE THREAD

**Issue by pajamaben1** [JEFF-Media-GbR/ChestSort#153]
**Used ChestSort version**
13.1.0

**Used Spigot version**
Paper 1.18.2 #333

**Other plugin used**
Sack (https://polymart.org/resource/sack-better-than-1-17-bundle.493)

**Describe the bug**
Doesn't register the bag inventory

**To Reproduce**
Give yourself a sack using /sack give (player) default 54 
Should give you a sack with 54 inventory slots, right click to open then try sorting

**Expected behavior**
Was hoping it would sort, I'm alright with it not working with sack since I'm basically using it instead of backpacks, but the spigot page said to submit if it wasn't working with 3rd party plugins

**Comment by mfnalex** [comment]
> but the spigot page said to submit if it wasn't working with 3rd party plugins

Oh yeah that's a bit outdated lol. I wrote that when ChestSort had like 500 downloads. Meanwhile it's over 100,000 downloads and if I'd add support for every third party plugin, then it would get reaaaally messy. Instead, other plugins are expected to hook into ChestSort, as that's the only proper solution.
