### ISSUE TITLE
Doesn't work with ironchest

### ISSUE THREAD

**Issue by D3v1lman** [JEFF-Media-GbR/ChestSort#159]
**Used ChestSort version**
I use ChestSort-13.4.0 version

**Used Spigot version**
I use the arclight 1.19.2 (36) version

**Other plugin used**
ironchest-1.19.2-14.2.7 version, https://www.curseforge.com/minecraft/mc-mods/iron-chests/files

**Describe the bug**
Ironchest chests do not take advantage of the chestsort functions, basically the items inside those chests are not sorted

**To Reproduce**
I don't know how could do it

**Expected behavior**
I expect that, I be able sort items automatically into ironchest's chests

**Additional context**
I am attaching the .jar file of the version of ironchest that I am using
Thank you for your trouble
[ironchest-1.19.2-14.2.7.zip](https://github.com/JEFF-Media-GbR/ChestSort/files/10180013/ironchest-1.19.2-14.2.7.zip)

**Comment by mfnalex** [comment]
Forge is not supported. ChestSort only supports servers running actual Spigot or one of its forks like Paper, Tuinity, ...
