### ISSUE TITLE
middle-click hotkey doesn't work

### ISSUE THREAD

**Issue by Swirlystefan** [JEFF-Media-GbR/ChestSort#160]
**Used ChestSort version**
13.4.0

**Used Spigot version**
git-Paper-305 (MC: 1.19.2)

**Describe the bug**
Fresh installation of chest sort. Middle-click hotkey doesn't work. The middle-click hotkey is enabled in config and gui.

**Additional context**
No errors or warnings. Other hotkeys work properly. E. g. double left click for sorting.

**Comment by mfnalex** [comment]
from the SpigotMC description page:
![image](https://user-images.githubusercontent.com/1122571/206697786-91b676eb-9b68-4e43-bb4f-496e2756a311.png)

**Comment by mfnalex** [comment]
If you have a suggestion for an alternative hotkey, please let me know. I couldn't think of any decent one yet

**Comment by Swirlystefan** [comment]
Thanks for your quick reply. I think the swap key 'F' would be a good option.

**Comment by mfnalex** [comment]
But that'd make players be unable to use F while having the inventory open. I formyself use that quite often :D
