### ISSUE TITLE
[Feature Request] Sort items into shulker boxes

### ISSUE THREAD

**Issue by MattAKAFred** [JEFF-Media-GbR/ChestSort#78]
**Describe the solution you'd like**
If a shulker box from within your inventory contains an item from your inventory, those items should be placed into the shulker box. e.g. if you have a shulker box with 1x 64 stack of cobble, and 4x 64 stacks of cobble in inventory, when sorting, you should end with 0 cobble in inventory and 5x 64 stacks of cobble in shulker box.

**Describe alternatives you've considered**
None - current system requires placing she shulker box, then auto-depositing or 

**Additional context**
Happy to attempt a PR for this, but wanted to discuss first - thoughts?

Probably needs a permission, or maybe just a config setting to enable/disable (permission may be better so servers can pitch it as a donor feature?)

Should the shulker box be sorted after having items deposited, or should items just be deposited, then sorted manually next time the box is accessed?

Should items sort into shulker boxes in toolbar if other toolbar sorting options are disabled?

I'm sure there's more questions, but those are what first come to mind....

**Comment by mfnalex** [comment]
Please see my comment in your PR
